apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  annotations:
    cosignexternaldata.datree.io/valid: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
        - image: noaabarki/webhook-server:latest
          name: webhook-server
          ports:
            - containerPort: 8443
              name: webhook-api
          volumeMounts:
            - name: tls
              mountPath: "/run/secrets/tls"
      volumes:
        - name: tls
          secret:
            secretName: webhook-server-tls
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lKQUo3dWRWLzB3cVZGTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ1l4Q3pBSkJnTlYKQkFZVEFrRlZNUmN3RlFZRFZRUUREQTUzWldKb2IyOXJMWE5sY25abGNqQWVGdzB5TXpBMk1qWXlNVE16TlRGYQpGdzB5TkRBMk1qVXlNVE16TlRGYU1DWXhDekFKQmdOVkJBWVRBa0ZWTVJjd0ZRWURWUVFEREE1M1pXSm9iMjlyCkxYTmxjblpsY2pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmRnOEg2VXNzbm0Ka0JwWUNOL3h0OFVKNm1KSGpadkV5cGhGNDJsSHlVOWNIazFXOWlsY2xuczA5UnhwZEgwOXhYNzdndUJKd0t0MApsblRuc1p3UEw1c0tmR2NVU28za3FvaVdLNnFkc2Nha25Rd1A5Sjl0aEhEY0x4SlR4MndBTC8wcWxaWUFFd2hWCkxYV243L0ZlQTMzWDhySnd0bGNuSXI4S3B4bDkrUStFdHMvRWpYbDhVQXlPTlFoazB4ZmVpRGhnRzdWci9WVDgKSm9takVCY2h0NzZzR2xMSVNodDNzc1BrSnN4SVI1alNqWkxaNFpjZ0QxNEdVK2NCU1JBTVRCREM0ZXRIdFZHVgpVZHNibVZsSU9WMWFqNmJTNHU2cDA2cWFhbGRHYkJoQzdYbUQxL2MzblRsOG56eERHeWUzRW1YelVPU0lYTStQCm5sUVQ5SkthZWo4Q0F3RUFBYU1wTUNjd0pRWURWUjBSQkI0d0hJSWFkMlZpYUc5dmF5MXpaWEoyWlhJdVpHVm0KWVhWc2RDNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUl4K0lUOEZwZ1d1K1dpNmczcFdrdUtUZ01hYgp4L2Jjb20zSTZQekZKZ1psWlVMaldXUWV4MTZVa29kRnVtQmpmMnRITW5SemV3ZDlzazVraHZXeTdXRjdQMEdkClhWUmxxaDZicGdFVzFmRG8wYTNjVTE1cFp4eU1XR3FWVFlUMjlMYXlXOC9HMDQxSlhDSXNrUkJEVE9SSWROZkIKdSs1WVgwM25FRDRlQTY4QmthSFovUGtERlB6bWZQZkRwdUpKamxnU3ZsaTZISWMxbkdrcnhEQTJ5OEFNK3pSaApJNXl1SzBEYUROUEJoN2hDeXZZRUNHWDFrbFR2Q2ExQ05tdnBnQjZBS1VvTDZqOHdTckZ4WHpJNkJrcUJCL3l2CkhwbjlwelZvTzdoUUwvWUVwS2VvVFVRTlIra01IWmdLaHBuamYyQW82ZW1BMVQxMGZ1V3JUZFRKNVpzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFhZUEIrbExMSjVwQWEKV0FqZjhiZkZDZXBpUjQyYnhNcVlSZU5wUjhsUFhCNU5WdllwWEpaN05QVWNhWFI5UGNWKys0TGdTY0NyZEpaMAo1N0djRHkrYkNueG5GRXFONUtxSWxpdXFuYkhHcEowTUQvU2ZiWVJ3M0M4U1U4ZHNBQy85S3BXV0FCTUlWUzExCnArL3hYZ045MS9LeWNMWlhKeUsvQ3FjWmZma1BoTGJQeEkxNWZGQU1qalVJWk5NWDNvZzRZQnUxYS8xVS9DYUoKb3hBWEliZStyQnBTeUVvYmQ3TEQ1Q2JNU0VlWTBvMlMyZUdYSUE5ZUJsUG5BVWtRREV3UXd1SHJSN1ZSbFZIYgpHNWxaU0RsZFdvK20wdUx1cWRPcW1tcFhSbXdZUXUxNWc5ZjNONTA1Zko4OFF4c250eEpsODFEa2lGelBqNTVVCkUvU1Ntbm8vQWdNQkFBRUNnZ0VBUzZsN2N3eHI3cSszcWZtSlRKck84MEp6ZTRrbGZ6Wlg4YnlEa21Xc205dUIKcmF2Q0dHKzFVWjBlQ3BnbFd5WUxMbnZPMDFvMWZFWWQ0UDNRRUVIcGVHN3JtdzZ1emtBcGhJZzAyT0JESnNTSApnMGhMcUlKQng2QWlUUzd2WE1xSUVVa1hlYldXK2hOcVArMzZSZkhBQ2tLRnVSZ05obnB5STJqcm9QSDNQL0s3ClVEUDFHbXVkWVJxSkJuMEVhUXE1UFBaY3AyWldKYW1udkFJSTZQNkpRSTY1bzVOdjdrNldlSEk2QnNvUnF6UE0KaTFhczdjM29XeFQydk9xQnJ2d0ZqS2lvUU1Jc1VYTmNUWUd0SlMrWW5mVjZ0dDF1Um5pYTZ1cFgyelZaMklMQQoxMlYrL3NTcWNXUTQ5eHQzcG8xcHFQMUlaeEJJVTB3SERRVlFLbThybVFLQmdRRDNGKzZBa3ZpdHZQdnRLSTN6CkJPM2lvUjdLamxGclNWQTFvbFZHaWh6ek5zT1dpdWFjUDVXd0ptM1JDS0E4cHFHTEtFazdUazJOdmtrcXJvdTcKN1laSzk3Qk9JWHU2bkhRdW92bGxGNVpNMGhjbkxBMXpWR3MyZVFDWUl1V1l3STdabll5SHl5MGZZT2hWOHEyMwprNlI0cHRKUkxDWWNNeXowcXhhNmkwY0V0UUtCZ1FEZkpGdU9mZXI5Zzd1cVdNWEdZR2drbkRyY1p3L3NXSGE5CjV5bHdiZUVzQ2lCM0NPSmM1dXNuRzdtMmV0dHhOL0FObjMyVHN1RlF4QTBSQVFiVVljaldLS0JPR1ZGQkxNRXUKUFhBUXdSSFVqYSt1TjFIaDZRRUg3Qm9zaFVxS3RuZDVNQm9vSU9HR2t2UXMzN2tOSXZvMnEwVTdmbXdjWTRvZgpEcXZYb3Zodm93S0JnSEQzSmZqdU9IYmxzWitKTE94djBub01BMUhEb3dHVHNQSDBWMXc2aEdYRkljSlBtb0xRCnB4U3pYUDEySGh2Y2FucCtYb3lZamVoQm1KM0UwdW1GL0NHRi83cVlvRUoraUxkUmx3ZGFzMEpId29JTUo5SVUKUkRmUk5pNVh0ZlFTQkwwRXhGekl6TVpOdmFxZG1rSVZZOW90R25ZMTR1NTlqdzRFc2cxeTQzTUpBb0dBQWdRQwpEN2R6ZC9iSXF6RkNHQmltMkMzUkdreVVDRDZFVkJMU2ZRR0JGelRBTmxNT09HaWRseXpZOEowTGZtcFM4TXlRCkJkV0gwNEx4MjBWM0dsUUh6R2R4aTBNUFNOZHVwMHhHeHQvM21VUHVZbFI5bU56UjlaQmNiQ3FJRWRpMEc1UWoKcUZranNHT0RjU1JVTjVvcFNIVWptdlg1WkFoQ0p5V3F4N2ZoSnFFQ2dZRUEwdUhteWZONittMUJYdndkWElwMgpNSmlXbEVITXdQRFoxNFNwYng1NXBvNDl6WUJLSldxSnV3Vm1XTXRnd1dScENsRThOSmFVWFBSbkJ2dFNObzVXCncwT05KU1hCRTUrMzIxdGxuUTRFQUFSVGNLWnBBS3NUVFN6aGM5ekoxRFNzZXBsZnRxMFZsaDNOOFRxUmMySXEKQnhIdCtPSDNOa3NlZ1dOQXpuc3hxd1k9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: webhook-server-tls
type: kubernetes.io/tls
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
spec:
  selector:
    app: webhook-server
  ports:
    - port: 443
      targetPort: webhook-api
