apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration #ValidatingWebhookConfiguration
metadata:
  name: "webhook"
webhooks:
  - name: "webhook-server.default.svc"
    admissionReviewVersions:
      - v1
      - v1beta1
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    clientConfig:
      service:
        namespace: default
        name: webhook-server
        path: /mutate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJBQ0NRQ1ZZRGdaVUEvYlRUQU5CZ2txaGtpRzl3MEJBUXNGQURBbU1Rc3dDUVlEVlFRR0V3SkIKVlRFWE1CVUdBMVVFQXd3T2QyVmlhRzl2YXkxelpYSjJaWEl3SGhjTk1qTXdOakkyTWpFek16VXhXaGNOTWpRdwpOakkxTWpFek16VXhXakFtTVFzd0NRWURWUVFHRXdKQlZURVhNQlVHQTFVRUF3d09kMlZpYUc5dmF5MXpaWEoyClpYSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEVDFId0RLSmZOa2ZVaU5kSzEKUlV5UnlHbWg2dUtNS2VmMUxuMDJ4QXpHcWY3UzlDTzFMMk5YeDZDVlh3Mm9SVmUya3ZOT3ZwTmI3QjZJQmxOUgpJUG01VmxiTjArNld3L0FQUDFKcWdIV3h1eWxLUW52dDNuRXU4OFlCclhnQ05OcFBXVGlIMHYvSjFrMjNKWExsCjNSTFVnNE5CQzIzc0JDem5vQUxwaTZsUXlCTjMzdlhUM0c2MFBSQ1NEbUdNM3RqbE5sYlRnSm5aUXFNT29ERU0KY3JoTHJMZk5nNWlpVHdnU0lMbUxuTXBVcUtad2dSSFc0Nm1MQlNLUWVWSFl6MFg5QUtHNEt5UFZySENHd09UYQo0b1Vwa0Y3NEVkVkVXeldxYzkxUXFJeDNvSmJUam9JOWhWYlZHY05lVDR5M2g3UXlOM2hEM09taUlZQldqYVFsCmdjZUJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDN1FmSVNnRzdYVW82VTBzU2YyWGhiQnBXY0cKWGMyaFZMSHVEUTAxbTlobUxzNFZxQndGOWR3SFo3Yk1ESUVUYXk5MldFYmZrMldPbkw4emVyeUZBaS9raXVHegpIVUhobzM0WjJtNzVKM3hEN1JUZXpzQWJ5aXlHRkpSdEFTd3hoMG9hQjVET0tmemJDeWRZY0syMzRSVGV0U3JPCm1DTDhSQnR0T2M5eG9oVEJwMGdWcWlha3EzYXhkS3plYkQwTFRERnZIbU9IRS83dGpqekU4V2QyZVB4dTNjeHMKaXd6VERWeTc1NGNLZmo2L0ptSU0yVzA4K0R2eUxZME9nWHI2SkxTd0NWU3pheWUyRnpqTS8wTVZXeDJnZzR0ZQpxdExpRzlQV1FhQlpMZ3hEbzB5Z1k2MThjL1Y4UTMweVZYbnB5di9DaUhTWi9SbXk2cFhwYVh1eHV5OD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
